---

all:
  children:
    # Master group, do not change the 'master' name
    # hosts should match the filenames in 'host_vars'
    master:
      hosts:
        node00:
    # Worker group, do not change the 'worker' name
    # hosts should match the filenames in 'host_vars'
    worker:
      hosts:
        node01:
        node02:
        node03:
        knode04:
    # Storage group, these are my NAS devices
    # hosts should match the filenames in 'host_vars'
    storage:
      hosts:
        nas01:
        # nas-serenity:
